[project]
name = "testing-pages"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "numpy>=2.2.6",
    "openai>=1.84.0",
    "pandas>=2.3.0",
    "pymongo>=4.13.0",
    "streamlit>=1.45.1",
]
